import { Dimensions, StyleSheet } from 'react-native';
import { color } from '../../color/color';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: color.white_FFFFFF },
  loadingContainer: { justifyContent: 'center', alignItems: 'center' },
  loadingText: { marginTop: 12 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingBottom: 2 },
  headerDivider: { height: 1.5, backgroundColor: '#E8E8E8', width: '100%', marginBottom: 24, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.02, shadowRadius: 2, elevation: 2 },
  headerButton: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center' },
  headerTitle: {},
  section: { marginBottom: 24 },
  happeningTodaySection: { backgroundColor: '#FFF6DF', paddingTop: 16, paddingBottom: 20, marginBottom: 24 },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', paddingHorizontal: 20, marginBottom: 16 },
  sectionTitleContainer: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  sectionTitle: {},
  sectionSubtitle: { marginTop: 2 },
  countdownContainer: { flexDirection: 'row', gap: 8 },
  countdownBox: { backgroundColor: color.white_FFFFFF, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, alignItems: 'center', minWidth: 55 },
  countdownNumber: {},
  countdownLabel: { marginTop: 2 },
  singleEventContainer: { paddingHorizontal: 20 },
  largeCard: { marginBottom: 16 },
  largeImageContainer: { height: 200 },
  largeImage: { width: '100%', height: '100%', resizeMode: 'cover', borderRadius: 8 },
  bookmarkButton: { position: 'absolute', top: 12, right: 12, padding: 8 },
  cardContent: { paddingTop: 10 },
  eventTitle: { marginBottom: 8 },
  eventDate: { marginBottom: 2 },
  eventTime: { marginBottom: 8 },
  eventLocation: {},
  horizontalList: { paddingRight: 20 },
  smallCard: { width: width * 0.55, marginRight: 12 },
  smallImageContainer: { height: 140 },
  smallImage: { width: '100%', height: '100%', borderRadius: 16 },
  bookmarkButtonSmall: { position: 'absolute', top: 10, right: 10, padding: 6 },
  smallCardContent: { paddingTop: 10 },
  smallEventTitle: { marginBottom: 6 },
  smallEventDate: { marginBottom: 2 },
  smallEventTime: { marginBottom: 6 },
  smallEventLocation: {},
  upcomingSection: { paddingHorizontal: 20 },
  upcomingItem: { flexDirection: 'row', borderRadius: 18, padding: 12, marginTop: 12, alignItems: 'center', backgroundColor: color.white_FFFFFF, shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.06, shadowRadius: 10, elevation: 1 },
  upcomingImage: { width: 70, height: 70, borderRadius: 12, resizeMode: 'cover' },
  upcomingContent: { flex: 1, marginLeft: 12 },
  upcomingTitle: { marginBottom: 4 },
  upcomingMeta: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  upcomingDate: {},
  upcomingDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: color.brown_766F6A, marginHorizontal: 8 },
  upcomingTime: {},
  upcomingLocation: {},
  upcomingBookmark: { padding: 8, paddingBottom: 65 },
  emptyState: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 60 },
  emptyStateText: {},
  bottomSpacer: { height: 40 },
});
