import { StyleSheet } from "react-native";
import { color } from "../../color/color";

export const styles = StyleSheet.create({
  mainContainer: { flex: 1 },
  scrollContainer: { paddingBottom: 20, flexGrow: 1 },
  wrapper: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 10,
    width: "100%",
    backgroundColor: color.btnBrown_AE6F28,
    height: 48,
  },
  headerBackButton: {
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 4,
  },
  headerContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "nowrap",
  },
  headerLeft: { flexDirection: "row", alignItems: "center", flexShrink: 1 },
  headerSpacer: { flex: 1 },
  dropdownButton: { marginLeft: 8, padding: 4 },
  eventName: { color: color.white_FFFFFF, fontSize: 14, fontWeight: "500" },
  cityName: { color: color.white_FFFFFF, fontSize: 12, fontWeight: "400" },
  date: { color: color.white_FFFFFF, fontSize: 12, fontWeight: "400" },
  time: { color: color.white_FFFFFF, fontSize: 12, fontWeight: "400" },
  labelDashboard: { color: color.brown_3C200A, paddingLeft: 10, marginTop: 10 },

  // ── AGENT tab bar ──
  agentTabContainer: {
    marginHorizontal: 16,
    marginVertical: 12,
  },
  agentTabRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  agentTabButton: {
    flex: 1,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 3,
    borderRadius: 7,
  },
  selectedAgentTabButton: {
    backgroundColor: color.white_FFFFFF,
    borderColor: color.white_FFFFFF,
  },
  agentTabButtonText: {
    color: color.black_544B45,
    fontSize: 13,
    fontWeight: "400",
  },
  selectedAgentTabButtonText: {
    color: color.placeholderTxt_24282C,
    fontWeight: "600",
  },

  // ── Shared tab styles ──
  tabContainer: { marginVertical: 8, marginHorizontal: 16 },
  tabRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
  },
  tabButton: {
    padding: 10,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    height: 40,
    marginHorizontal: 2,
  },
  tabButtonText: {
    color: color.black_544B45,
    textAlign: "center",
    fontSize: 14,
    fontWeight: "400",
    flexWrap: "wrap",
    numberOfLines: 2,
  },
  selectedTabButton: {
    flex: 1,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: color.white_FFFFFF,
    borderRadius: 7,
    backgroundColor: color.white_FFFFFF,
    marginHorizontal: 2,
  },
  selectedTabButtonText: {
    color: color.placeholderTxt_24282C,
    textAlign: "center",
    fontSize: 14,
    flexWrap: "wrap",
    numberOfLines: 2,
    fontWeight: "500",
  },
  loadingText: { textAlign: "center", padding: 20, color: color.brown_3C200A },
  errorText: { textAlign: "center", padding: 20, color: "red" },
  separator: {
    fontSize: 12,
    fontWeight: "400",
    color: color.white_FFFFFF,
    marginHorizontal: 4,
  },
  saleScanTabContainer: { marginHorizontal: 16, marginVertical: 8 },
  saleScanTabRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
  },
  saleScanTabButton: {
    marginTop: 3,
    padding: 10,
    width: "50%",
    justifyContent: "center",
    alignItems: "center",
    height: 40,
  },
  saleScanTabButtonText: {
    color: color.black_544B45,
    fontWeight: "400",
    fontSize: 14,
  },
  adminTabContainer: { marginHorizontal: 16, marginVertical: 20 },
  adminTabRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
  },
  adminTabButton: {
    padding: 10,
    width: "33%",
    justifyContent: "center",
    alignItems: "center",
    height: 40,
  },
  adminTabButtonText: {
    color: color.black_544B45,
    fontWeight: "400",
    fontSize: 14,
  },
  selectedAdminTabButton: {
    width: "33%",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: color.white_FFFFFF,
    borderRadius: 7,
    backgroundColor: color.white_FFFFFF,
  },
  selectedAdminTabButtonText: {
    color: color.placeholderTxt_24282C,
    fontWeight: "500",
    fontSize: 14,
  },
  adminOnlineBoxOfficeTabContainer: { marginHorizontal: 16, marginVertical: 8 },
  adminOnlineBoxOfficeTabRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
  },
  adminOnlineBoxOfficeTabButton: {
    padding: 10,
    width: "32%",
    justifyContent: "center",
    alignItems: "center",
    height: 40,
    backgroundColor: "#F7E4B690",
    borderColor: "#F7E4B690",
    borderRadius: 7,
    borderWidth: 1,
  },
  adminOnlineBoxOfficeTabButtonText: {
    color: color.black_544B45,
    fontSize: 14,
    fontWeight: "400",
  },
  selectedAdminOnlineBoxOfficeTabButton: {
    width: "32%",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: color.btnBrown_AE6F28,
    borderRadius: 7,
    backgroundColor: color.btnBrown_AE6F28,
  },
  selectedAdminOnlineBoxOfficeTabButtonText: {
    color: color.white_FFFFFF,
    fontWeight: "500",
    fontSize: 14,
  },
  selectedSaleScanTabButton: {
    width: "50%",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: color.white_FFFFFF,
    borderRadius: 7,
    backgroundColor: color.white_FFFFFF,
  },
  selectedSaleScanTabButtonText: {
    color: color.placeholderTxt_24282C,
    fontWeight: "500",
    fontSize: 14,
  },
  overallStatisticsContainer: { marginTop: 4 },
  headerButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  availableTicketsContainer: {
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
  },
  availableTicketsOuterWrapper: {
    backgroundColor: color.white_FFFFFF,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: color.white_FFFFFF,
    padding: 16,
  },
  availableTicketsCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    backgroundColor: color.white_FFFFFF,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: color.brown_CEBCA04D,
    gap: 12,
  },
  availableTicketsTextContainer: { flex: 1 },
  availableTicketsTitle: {
    fontSize: 12,
    color: color.placeholderTxt_24282C,
    fontWeight: "400",
  },
  availableTicketsValue: {
    fontSize: 14,
    fontWeight: "500",
    marginTop: 4,
    color: color.brown_3C200A,
  },
});
