import { StyleSheet } from 'react-native';
import { color } from '../../color/color';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 120,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    paddingBottom: 12,
    backgroundColor: '#FFFFFF',
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  screenTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: color.brown_3C200A,
  },
  profileSection: {
    alignItems: 'center',
    paddingTop: 20,
    paddingBottom: 16,
  },
  avatarWrapper: {
    width: 104,
    height: 104,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  avatarContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: color.btnBrown_AE6F28,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  avatar: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  cameraIconContainer: {
    position: 'absolute',
    bottom: -10,
    left: 36,
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: color.btnBrown_AE6F28,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
    elevation: 2,
  },
  userName: {
    fontSize: 20,
    fontWeight: '600',
    color: color.brown_3C200A,
    marginBottom: 4,
    paddingTop: 28,
  },
  formSection: {
    paddingHorizontal: 20,
    paddingTop: 8,
    gap: 4,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: color.brown_3C200A,
    marginBottom: 6,
  },
  textInput: {
    borderWidth: 1.5,
    borderColor: '#E8DDD3',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    color: color.brown_3C200A,
    backgroundColor: '#FAFAFA',
  },
  readOnlyInput: {
    backgroundColor: '#F5F0EB',
    borderColor: '#E0D6CC',
    justifyContent: 'center',
  },
  readOnlyText: {
    fontSize: 15,
    color: '#8A7060',
  },
  menuSection: {
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    marginTop: 8,
  },
  logoutText: {
    marginLeft: 15,
    fontSize: 16,
    color: color.btnBrown_AE6F28,
    fontWeight: '500',
  },
  saveButton: {
    backgroundColor: color.btnBrown_AE6F28,
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 24,
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
  },
  saveButtonText: {
    color: color.btnTxt_FFF6DF,
    fontSize: 16,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  logoutSheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 24,
    paddingTop: 12,
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E0D6CC',
    alignSelf: 'center',
    marginBottom: 20,
  },
  sheetTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: color.brown_3C200A,
    textAlign: 'center',
    marginBottom: 8,
  },
  sheetSubtitle: {
    fontSize: 14,
    color: '#87807C',
    textAlign: 'center',
    marginBottom: 28,
  },
  sheetButtonRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 4,
  },
  sheetLogoutButton: {
    flex: 1,
    backgroundColor: color.btnBrown_AE6F28,
    borderRadius: 22,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
  },
  sheetLogoutButtonText: {
    color: color.btnTxt_FFF6DF,
    fontSize: 15,
    fontWeight: '700',
  },
  sheetCancelButton: {
    flex: 1,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: '#E0D6CC',
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetCancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: color.brown_3C200A,
  },
});
