import { StyleSheet } from 'react-native';
import { color } from '../../color/color';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 100,
  },
  profileSection: {
    alignItems: 'center',
    padding: 20,
    paddingTop: 50,
  },
  avatarWrapper: {
    width: 104,
    height: 104,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  avatarContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: color.btnBrown_AE6F28,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  avatar: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  cameraIconContainer: {
    position: 'absolute',
    bottom: -16,
    left: '50%',
    transform: [{ translateX: -16 }],
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: color.btnBrown_AE6F28,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
    elevation: 2,
  },
  userName: {
    fontSize: 20,
    fontWeight: '600',
    color: color.brown_3C200A,
    marginBottom: 5,
    paddingTop: 30,
  },
  menuSection: {
    padding: 20,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    marginTop: 15,
  },
  logoutText: {
    marginLeft: 15,
    fontSize: 16,
    color: color.btnBrown_AE6F28,
    fontWeight: '500',
  },
  saveButton: {
    backgroundColor: color.btnBrown_AE6F28,
    borderRadius: 16,
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 24,
    marginBottom: 30,
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
  },
  saveButtonText: {
    color: color.btnTxt_FFF6DF,
    fontSize: 16,
    fontWeight: '700',
  },
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 30,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
