import { StyleSheet } from "react-native";
import { color } from "../../../color/color";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 16,
  },
  headerLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
  headerRight: { flexDirection: "row", alignItems: "center", gap: 12 },
  bellButton: { position: "relative" },
  headerDivider: { width: 2, height: 40, backgroundColor: color.grey_E5E7EB },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: color.btnBrown_AE6F28,
    justifyContent: "center",
    alignItems: "center",
  },
  filters: {
    flexDirection: "row",
    paddingHorizontal: 20,
    gap: 12,
    marginBottom: 12,
    width: "100%",
  },
  filtersRow2: {
    flexDirection: "row",
    paddingHorizontal: 20,
    gap: 12,
    marginBottom: 16,
    width: "100%",
  },
  dropdownWrapper: { flex: 1.22 },
  dateSelectorInRow: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: color.white_FFFFFF,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 8,
    borderWidth: 0.1,
    borderColor: color.grey_DADADA,
    justifyContent: "space-between",
  },
  dateSelectorText: { flex: 1, fontSize: 14, color: color.brown_766F6A },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
    paddingBottom: 60,
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: color.brown_3C200A,
    marginTop: 20,
    marginBottom: 8,
    textAlign: "center",
  },
  errorSubtitle: {
    fontSize: 14,
    color: color.brown_766F6A,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 28,
  },
  retryButton: {
    backgroundColor: color.btnBrown_AE6F28,
    paddingHorizontal: 44,
    paddingVertical: 14,
    borderRadius: 24,
  },
  retryButtonText: {
    color: color.white_FFFFFF,
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
});
