import { Dimensions, Platform, StyleSheet } from "react-native";
import { color } from "../../../color/color";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1, 
    // backgroundColor: color.white_FFFFFF 
  },
  loadingContainer: { justifyContent: "center", alignItems: "center" },
  loadingText: { marginTop: 12 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 2,
    paddingTop:Platform.OS=='android'?40:60
  },
  headerDivider: {
    height: 1.5,
    backgroundColor: "#E8E8E8",
    width: "100%",
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 2,
    elevation: 2,
  },
  headerButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {},
  section: { marginBottom: 24 },
  happeningTodaySection: {
    backgroundColor: "#FFF6DF",
    paddingTop: 16,
    paddingBottom: 20,
    marginBottom: 24,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  sectionTitleContainer: { flexDirection: "row", alignItems: "center", gap: 4 },
  sectionTitle: {},
  sectionSubtitle: { marginTop: 2 },
  countdownContainer: { flexDirection: "row", gap: 8 },
  countdownBox: {
    backgroundColor: color.white_FFFFFF,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: "center",
    minWidth: 55,
  },
  countdownNumber: {},
  countdownLabel: { marginTop: 2 },
  singleEventContainer: { paddingHorizontal: 20 },
  largeCard: { marginBottom: 16 },
  largeImageContainer: { height: 200 },
  largeImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
    borderRadius: 8,
  },
  bookmarkButton: { position: "absolute", top: 12, right: 12, padding: 8 },
  cardContent: { paddingTop: 10 },
  eventTitle: { marginBottom: 8 },
  eventDate: { marginBottom: 2 },
  eventTime: { marginBottom: 8 },
  eventLocation: {},
  horizontalList: { paddingRight: 20 },
  smallCard: { width: width * 0.55, marginRight: 12 },
  smallImageContainer: { height: 140 },
  smallImage: { width: "100%", height: "100%", borderRadius: 16 },
  bookmarkButtonSmall: { position: "absolute", top: 10, right: 10, padding: 6 },
  smallCardContent: { paddingTop: 10 },
  smallEventTitle: { marginBottom: 6 },
  smallEventDate: { marginBottom: 2 },
  smallEventTime: { marginBottom: 6 },
  smallEventLocation: {},
  upcomingSection: { paddingHorizontal: 20 },
  upcomingItem: {
    flexDirection: "row",
    borderRadius: 18,
    padding: 12,
    marginTop: 12,
    alignItems: "center",
    backgroundColor: color.white_FFFFFF,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 1,
  },
  upcomingImage: {
    width: 70,
    height: 70,
    borderRadius: 12,
    resizeMode: "cover",
  },
  upcomingContent: { flex: 1, marginLeft: 12 },
  upcomingTitle: { marginBottom: 4 },
  upcomingMeta: { flexDirection: "row", alignItems: "center", marginBottom: 4 },
  upcomingDate: {},
  upcomingDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: color.brown_766F6A,
    marginHorizontal: 8,
  },
  upcomingTime: {},
  upcomingLocation: {},
  upcomingBookmark: { padding: 8, paddingBottom: 65 },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
  },
  emptyStateText: {},
  bottomSpacer: { height: 40 },

  // Stats row
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    gap: 8,
  },
  statCard: {
    flex: 1,
    backgroundColor: color.white_FFFFFF,
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },

  // List header label row
  listHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginBottom: 12,
  },

  // Event card
  eventCard: {
    marginHorizontal: 20,
    marginBottom: 16,
    backgroundColor: color.white_FFFFFF,
    borderRadius: 16,
    overflow: "hidden",
    // shadowColor: "#000",
    // shadowOffset: { width: 0, height: 4 },
    // shadowOpacity: 0.07,
    // shadowRadius: 10,
    // elevation: 3,
  },
  eventCardImage: { width: "100%", height: 180 },
  statusBadge: {
    position: "absolute",
    top: 12,
    left: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(0,0,0,0.55)",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  eventCardContent: { padding: 14 },
  eventCardTitle: { marginBottom: 6 },
  eventCardMeta: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  metaDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: color.grey_87807C,
    marginHorizontal: 6,
  },
  eventCardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },

  // FlatList content
  listContent: { paddingBottom: 40 },

  // Load more
  loadMoreIndicator: { paddingVertical: 20 },

  // Search bar
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 16,
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: "#FFF",
    borderRadius: 24,
    gap: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: "#2F251D",
    paddingVertical: 0,
  },
  searchClearButton: { padding: 4 },

  clearAllButton: { marginTop: 12, paddingVertical: 8, paddingHorizontal: 16 },
});
